# This is a basic workflow to help you get started with Actions

name: helloWorld

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest
  
    defaults:
      run:
        shell: bash
        working-directory: hello_world
      
    
    steps: 

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
        
      - name: npm install, Deploy
        run: 
          npm install
          npm deploy

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo goodbye
